// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZn7FoqUs-iTD-jLAcLyHu2gRItXFblfs',
    appId: '1:759177786786:web:06ccb7efac4f1934f22efb',
    messagingSenderId: '759177786786',
    projectId: 'flutter-ai-playground-aadf5',
    authDomain: 'flutter-ai-playground-aadf5.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-aadf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKdTeVPEaP2-yHDPHaMEwuBkOj2bYmfA',
    appId: '1:759177786786:android:87f80946d2a49aa2f22efb',
    messagingSenderId: '759177786786',
    projectId: 'flutter-ai-playground-aadf5',
    storageBucket: 'flutter-ai-playground-aadf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuARMyzfMIqrGUXwXW2aFj72hlwLa8P10',
    appId: '1:759177786786:ios:e666ab6dbdf4e410f22efb',
    messagingSenderId: '759177786786',
    projectId: 'flutter-ai-playground-aadf5',
    storageBucket: 'flutter-ai-playground-aadf5.firebasestorage.app',
    iosBundleId: 'com.example.toolBocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuARMyzfMIqrGUXwXW2aFj72hlwLa8P10',
    appId: '1:759177786786:ios:e666ab6dbdf4e410f22efb',
    messagingSenderId: '759177786786',
    projectId: 'flutter-ai-playground-aadf5',
    storageBucket: 'flutter-ai-playground-aadf5.firebasestorage.app',
    iosBundleId: 'com.example.toolBocs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZn7FoqUs-iTD-jLAcLyHu2gRItXFblfs',
    appId: '1:759177786786:web:8b808532f84d1f3ef22efb',
    messagingSenderId: '759177786786',
    projectId: 'flutter-ai-playground-aadf5',
    authDomain: 'flutter-ai-playground-aadf5.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-aadf5.firebasestorage.app',
  );

}